name: Documentation Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - 'docs/**'
      - '.markdownlint.json'
      - '.github/workflows/docs-quality.yml'

jobs:
  markdown-lint:
    name: Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run markdownlint
        run: npm run lint:docs

  link-check:
    name: Internal Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check internal links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --exclude-all-private --exclude-mail --accept 200,204,301,302,403,429,999 'docs/**/*.md' 'docs/**/*.mdx'
          fail: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  front-matter-check:
    name: Front Matter Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check front matter consistency
        run: |
          echo "Checking front matter consistency..."
          find docs -name "*.md" -o -name "*.mdx" | while read file; do
            if head -n 1 "$file" | grep -q "^---$"; then
              if ! head -n 20 "$file" | tail -n +2 | grep -q "^---$"; then
                echo "Error: $file has opening front matter delimiter but no closing delimiter"
                exit 1
              fi
            fi
          done
          echo "Front matter validation passed"
