name: CICD Trivy Scan - Javelin Documentation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - "dev"
      - "main"
  merge_group:
    types:
      - checks_requested

jobs:
  reusable-workflow:
    permissions:
      contents: 'read'
      id-token: 'write'
      actions: 'read'
      security-events: 'write'
    uses: getjavelin/javelin-workflow/.github/workflows/workflow-trivy-scan.yml@main
    secrets:
      DEVOPS_GITHUB_TOKEN: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}